version: '3.8'

services:
  web:
    build: .
    # command: ./entrypoint.sh
    volumes:
      - .:/usr/src/app
      - .db_data/db.sqlite3:/db.sqlite3
    ports:
      - "8000:8000"
  web_migrate:
    extends:
      service: web
  command: python manage.py migrate
  web_run:
    extends:
      service: web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"