# Utilizar la imagen oficial de Python 3
FROM python:3.9.15-alpine3.16

# Seleccionar el directorio donde trabajaremos
WORKDIR /usr/src/app

# Establecemos algunas variables de entorno
# PYTHONDONTWRITEBYTECODE Evita que Python escriba archivos pyc en el disco
# PYTHONUNBUFFERED evita que Python almacene en búfer stdout y stderr
ENV PYTHONDONTWRITEBYTECODE 1 
ENV PYTHONUNBUFFERED 1

# install psycopg2 dependencies
RUN apk update \
    && apk add postgresql-dev gcc python3-dev musl-dev

# Instalar dependencias.
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt --no-color


# Copiar entrypoint.sh que verifica si la BD se encuentra en buen estado antes de hacer las migraciones
COPY ./entrypoint.sh .
RUN sed -i 's/\r$//g' /usr/src/app/entrypoint.sh
RUN chmod +x /usr/src/app/entrypoint.sh

# Copiar el codigo fuente al directorio de trabajo
COPY . .

# Ejecuta entrypoint.sh
ENTRYPOINT ["/usr/src/app/entrypoint.sh"]

# Abrir el puerto 80 del contendor
#EXPOSE 8000

#CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]